Hw03 mongodb
Den4yk76/nodejs-homework-rest-api pull request #2
Opened 2021-12-24 20:30 UTC by Den4yk76

Готово. Проверьте пожалуйста.

2021-12-26 13:55 UTC, KirillKulakow commented on app.js
> +import contactsRouter from './routes/api/contacts/index.js';
разницы между импортом `from './routes/api/contacts/index.js';` и `from './routes/api/contacts';` нет никакой, так зачем писать больше?

2021-12-26 13:55 UTC, KirillKulakow commented on controllers/contacts/index.js
> +  console.log(contact); // toObject
зачем лог?

2021-12-26 14:01 UTC, KirillKulakow commented on controllers/contacts/index.js
> +    .json({ status: 'success', code: HttpCode.OK, data: { ...contacts } });
объясни в чем смысл данной строки - которую ты написал?
`data: { ...contacts }`

2021-12-26 14:02 UTC, KirillKulakow commented on controllers/contacts/index.js
> +    .json({ status: 'success', code: HttpCode.OK, data: { ...contacts } });
жду в слак

2021-12-26 14:02 UTC, Den4yk76 commented on app.js
> +import contactsRouter from './routes/api/contacts/index.js';
иначе почему то било какую-то ошибку, типа миссинг модуль или вроде того

2021-12-26 14:04 UTC, KirillKulakow requested changes
Need fix

2021-12-27 19:11 UTC, KirillKulakow approved these changes

2021-12-28 17:29 UTC, merged