Hw05 avatars
Den4yk76/nodejs-homework-rest-api pull request #4
Opened 2022-01-12 18:08 UTC by Den4yk76

Сделал без доп заданий. Не получается настроить Jest под es6 модули. Дополнительные задания сделаю, но после вебинара по тестированию. 
Проверьте пожалуйста

2022-01-12 20:52 UTC, KirillKulakow approved these changes

2022-01-12 20:55 UTC, KirillKulakow commented on controllers/auth/index.js
>  const registration = async (req, res, next) => {
не вижу использования gravatar?

2022-01-12 20:55 UTC, KirillKulakow requested changes
Need fix

2022-01-12 21:38 UTC, Den4yk76 commented on controllers/auth/index.js
>  const registration = async (req, res, next) => {
Gravatar же в моделе в свойстве avatarUrl по умолчанию используется

2022-01-13 21:21 UTC, KirillKulakow approved these changes

2022-01-13 21:40 UTC, merged